package ustc.yzwx.integration.activity.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import ustc.yzwx.common.integration.dao.annotation.DaoMaster;
import ustc.yzwx.presentation.activity.form.Activity;

@DaoMaster
public interface ActivityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_activity
     *
     * @mbggenerated Wed Feb 19 09:53:20 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_activity
     *
     * @mbggenerated Wed Feb 19 09:53:20 CST 2014
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_activity
     *
     * @mbggenerated Wed Feb 19 09:53:20 CST 2014
     */
    int insertSelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_activity
     *
     * @mbggenerated Wed Feb 19 09:53:20 CST 2014
     */
    Activity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_activity
     *
     * @mbggenerated Wed Feb 19 09:53:20 CST 2014
     */
    int updateByPrimaryKeySelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_activity
     *
     * @mbggenerated Wed Feb 19 09:53:20 CST 2014
     */
    int updateByPrimaryKey(Activity record);
    /**
     * 查询所有活动
     * @return 活动集合
     */
    public List<Activity> findAll();
    /**
     * 查询所有活动（分页）
     * @param offset 起始页数
     * @param limit  每页显示数
     * @return 活动集合
     */
    public List<Activity> findall(@Param("name") String name,@Param("offset") int offset, @Param("limit") int limit);
    /**
     * 查询所有活动数目
     * @return 活动数目
     */
    public int totalCount(@Param("name") String name);
    
    
}