package com.zkhy.integration.manager.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zkhy.common.integration.dao.annotation.DaoMaster;
import com.zkhy.integration.manager.dao.seachObj.ManagerSeachObj;
import com.zkhy.presentation.manager.form.Manager;

@DaoMaster
public interface ManagerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	int deleteByPrimaryKey(Integer managerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	int insert(Manager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	int insertSelective(Manager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	Manager selectByPrimaryKey(Integer managerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	int updateByPrimaryKeySelective(Manager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	int updateByPrimaryKey(Manager record);
	
	/**
	 * 根据用户名查询管理员
	 * @param name
	 * @return
	 */
	Manager findManagerByUserName(@Param("name")String name);
	
	/**
	 * 查询所有二级管理员
	 * @param offset  起始页数
	 * @param limit   一页显示数
	 * @return
	 */
	List<Manager> getAllManager(ManagerSeachObj obj);
	
	int getAllManagerCount(ManagerSeachObj obj);
	
}