package ustc.yzwx.presentation.admin.form;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_admin.id
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_admin.name
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_admin.password
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_admin.salt
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_admin.status
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_admin.id
     *
     * @return the value of wx_admin.id
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_admin.id
     *
     * @param id the value for wx_admin.id
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_admin.name
     *
     * @return the value of wx_admin.name
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_admin.name
     *
     * @param name the value for wx_admin.name
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_admin.password
     *
     * @return the value of wx_admin.password
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_admin.password
     *
     * @param password the value for wx_admin.password
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_admin.salt
     *
     * @return the value of wx_admin.salt
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_admin.salt
     *
     * @param salt the value for wx_admin.salt
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_admin.status
     *
     * @return the value of wx_admin.status
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_admin.status
     *
     * @param status the value for wx_admin.status
     *
     * @mbggenerated Thu Feb 27 14:13:38 CST 2014
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}