package com.zkhy.web.integration.index.dao;

import java.util.List;

import com.zkhy.fw.integration.dao.annotation.DaoMaster;
import com.zkhy.web.integration.index.entity.TimeLineEntity;
@DaoMaster
public interface TimeLineDao {
    List<TimeLineEntity> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timeline
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    int deleteByPrimaryKey(Integer dateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timeline
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    int insert(TimeLineEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timeline
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    int insertSelective(TimeLineEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timeline
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    TimeLineEntity selectByPrimaryKey(Integer dateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timeline
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    int updateByPrimaryKeySelective(TimeLineEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timeline
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    int updateByPrimaryKey(TimeLineEntity record);
}