package ustc.yzwx.integration.student.dao;

import java.util.List;
import java.util.Map;

import ustc.yzwx.common.integration.dao.annotation.DaoMaster;
import ustc.yzwx.presentation.student.form.StudentMajor;

@DaoMaster
public interface StudentMajorDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_student_major
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_student_major
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    int insert(StudentMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_student_major
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    int insertSelective(StudentMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_student_major
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    StudentMajor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_student_major
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    int updateByPrimaryKeySelective(StudentMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_student_major
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    int updateByPrimaryKey(StudentMajor record);
    
    /**
     * 根据考生ID查报考专业
     * @param studentId
     * @return List
     */
    List<Map<String,Object>> selectByStudentId(int studentId);
    
    /**
     * 根据考生ID删除
     * @param studentId
     */
    void deleteByStudentId(int studentId);
}