package com.zkhy.web.integration.index.dao;

import java.util.List;

import com.zkhy.fw.integration.dao.annotation.DaoMaster;
import com.zkhy.web.integration.index.entity.TimeLineDetailEntity;
@DaoMaster
public interface TimeLineDetailDao {
    List<TimeLineDetailEntity> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timeline_detail
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    int deleteByPrimaryKey(Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timeline_detail
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    int insert(TimeLineDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timeline_detail
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    int insertSelective(TimeLineDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timeline_detail
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    TimeLineDetailEntity selectByPrimaryKey(Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timeline_detail
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    int updateByPrimaryKeySelective(TimeLineDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_timeline_detail
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    int updateByPrimaryKey(TimeLineDetailEntity record);
}