package com.zkhy.web.integration.index.entity;

import java.util.Date;

import com.zkhy.fw.integration.entity.BaseEntity;

public class TimeLineDetailEntity extends BaseEntity {
    private static final long serialVersionUID = -8467857101719025222L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_timeline_detail.ACTIVITY_ID
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    private int activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_timeline_detail.DATE_ID
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    private int dateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_timeline_detail.ACTIVITY_START
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    private Date activityStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_timeline_detail.ACTIVITY_END
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    private Date activityEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_timeline_detail.ACTIVITY_CONTENT
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    private String activityContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_timeline_detail.ACTIVITY_ID
     *
     * @return the value of t_timeline_detail.ACTIVITY_ID
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    public int getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_timeline_detail.ACTIVITY_ID
     *
     * @param activityId the value for t_timeline_detail.ACTIVITY_ID
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    public void setActivityId(int activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_timeline_detail.DATE_ID
     *
     * @return the value of t_timeline_detail.DATE_ID
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    public int getDateId() {
        return dateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_timeline_detail.DATE_ID
     *
     * @param dateId the value for t_timeline_detail.DATE_ID
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    public void setDateId(int dateId) {
        this.dateId = dateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_timeline_detail.ACTIVITY_START
     *
     * @return the value of t_timeline_detail.ACTIVITY_START
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    public Date getActivityStart() {
        return activityStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_timeline_detail.ACTIVITY_START
     *
     * @param activityStart the value for t_timeline_detail.ACTIVITY_START
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    public void setActivityStart(Date activityStart) {
        this.activityStart = activityStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_timeline_detail.ACTIVITY_END
     *
     * @return the value of t_timeline_detail.ACTIVITY_END
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    public Date getActivityEnd() {
        return activityEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_timeline_detail.ACTIVITY_END
     *
     * @param activityEnd the value for t_timeline_detail.ACTIVITY_END
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    public void setActivityEnd(Date activityEnd) {
        this.activityEnd = activityEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_timeline_detail.ACTIVITY_CONTENT
     *
     * @return the value of t_timeline_detail.ACTIVITY_CONTENT
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    public String getActivityContent() {
        return activityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_timeline_detail.ACTIVITY_CONTENT
     *
     * @param activityContent the value for t_timeline_detail.ACTIVITY_CONTENT
     *
     * @mbggenerated Mon Apr 07 18:09:34 CST 2014
     */
    public void setActivityContent(String activityContent) {
        this.activityContent = activityContent == null ? null : activityContent.trim();
    }
}