package com.zkhy.web.integration.index.entity;

import java.util.Date;

import com.zkhy.fw.integration.entity.BaseEntity;

public class TimeLineEntity extends BaseEntity {
    private static final long serialVersionUID = -5791886490654530524L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_timeline.DATE_ID
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    private int dateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_timeline.DATE_START
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    private Date dateStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_timeline.DATE_END
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    private Date dateEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_timeline.DATE_ID
     *
     * @return the value of t_timeline.DATE_ID
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    public int getDateId() {
        return dateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_timeline.DATE_ID
     *
     * @param dateId the value for t_timeline.DATE_ID
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    public void setDateId(int dateId) {
        this.dateId = dateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_timeline.DATE_START
     *
     * @return the value of t_timeline.DATE_START
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    public Date getDateStart() {
        return dateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_timeline.DATE_START
     *
     * @param dateStart the value for t_timeline.DATE_START
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_timeline.DATE_END
     *
     * @return the value of t_timeline.DATE_END
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    public Date getDateEnd() {
        return dateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_timeline.DATE_END
     *
     * @param dateEnd the value for t_timeline.DATE_END
     *
     * @mbggenerated Mon Apr 07 18:07:22 CST 2014
     */
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }
}