package ustc.yzwx.presentation.student.form;

public class Region {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_region.id
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_region.code
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_region.name
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_region.parent_id
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_region.status
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_region.id
     *
     * @return the value of wx_region.id
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_region.id
     *
     * @param id the value for wx_region.id
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_region.code
     *
     * @return the value of wx_region.code
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_region.code
     *
     * @param code the value for wx_region.code
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_region.name
     *
     * @return the value of wx_region.name
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_region.name
     *
     * @param name the value for wx_region.name
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_region.parent_id
     *
     * @return the value of wx_region.parent_id
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_region.parent_id
     *
     * @param parentId the value for wx_region.parent_id
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_region.status
     *
     * @return the value of wx_region.status
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_region.status
     *
     * @param status the value for wx_region.status
     *
     * @mbggenerated Wed Feb 26 11:04:33 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}