package ustc.yzwx.presentation.student.form;

public class School {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_school.id
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_school.name
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_school.province
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_school.city
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_school.type
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_school.id
     *
     * @return the value of wx_school.id
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_school.id
     *
     * @param id the value for wx_school.id
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_school.name
     *
     * @return the value of wx_school.name
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_school.name
     *
     * @param name the value for wx_school.name
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_school.province
     *
     * @return the value of wx_school.province
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_school.province
     *
     * @param province the value for wx_school.province
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_school.city
     *
     * @return the value of wx_school.city
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_school.city
     *
     * @param city the value for wx_school.city
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_school.type
     *
     * @return the value of wx_school.type
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_school.type
     *
     * @param type the value for wx_school.type
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}