package ustc.yzwx.presentation.student.form;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student.id
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student.wx_code
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    private String wxCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student.name
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student.school_id
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student.major_code
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    private String majorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student.email
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student.contact
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student.gpa
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    private Float gpa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student.status
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student.student_major
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    private String studentMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student.class_size
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    private Integer classSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student.student_rank
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    private Integer studentRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student.gpa_img
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    private byte[] gpaImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student.id
     *
     * @return the value of wx_student.id
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    
    private String idCardNum;
    
    private School school;
    
    private Major major;
    
    public School getSchool() {
		return school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	public Major getMajor() {
		return major;
	}

	public void setMajor(Major major) {
		this.major = major;
	}

    public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student.wx_code
     *
     * @return the value of wx_student.wx_code
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public String getWxCode() {
        return wxCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student.wx_code
     *
     * @param wxCode the value for wx_student.wx_code
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public void setWxCode(String wxCode) {
        this.wxCode = wxCode == null ? null : wxCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student.name
     *
     * @return the value of wx_student.name
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student.name
     *
     * @param name the value for wx_student.name
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student.school_id
     *
     * @return the value of wx_student.school_id
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student.school_id
     *
     * @param schoolId the value for wx_student.school_id
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student.major_code
     *
     * @return the value of wx_student.major_code
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public String getMajorCode() {
        return majorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student.major_code
     *
     * @param majorCode the value for wx_student.major_code
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public void setMajorCode(String majorCode) {
        this.majorCode = majorCode == null ? null : majorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student.email
     *
     * @return the value of wx_student.email
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student.email
     *
     * @param email the value for wx_student.email
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student.contact
     *
     * @return the value of wx_student.contact
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student.contact
     *
     * @param contact the value for wx_student.contact
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student.gpa
     *
     * @return the value of wx_student.gpa
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public Float getGpa() {
        return gpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student.gpa
     *
     * @param gpa the value for wx_student.gpa
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public void setGpa(Float gpa) {
        this.gpa = gpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student.status
     *
     * @return the value of wx_student.status
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student.status
     *
     * @param status the value for wx_student.status
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student.student_major
     *
     * @return the value of wx_student.student_major
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public String getStudentMajor() {
        return studentMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student.student_major
     *
     * @param studentMajor the value for wx_student.student_major
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public void setStudentMajor(String studentMajor) {
        this.studentMajor = studentMajor == null ? null : studentMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student.class_size
     *
     * @return the value of wx_student.class_size
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public Integer getClassSize() {
        return classSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student.class_size
     *
     * @param classSize the value for wx_student.class_size
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public void setClassSize(Integer classSize) {
        this.classSize = classSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student.student_rank
     *
     * @return the value of wx_student.student_rank
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public Integer getStudentRank() {
        return studentRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student.student_rank
     *
     * @param studentRank the value for wx_student.student_rank
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public void setStudentRank(Integer studentRank) {
        this.studentRank = studentRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student.gpa_img
     *
     * @return the value of wx_student.gpa_img
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public byte[] getGpaImg() {
        return gpaImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student.gpa_img
     *
     * @param gpaImg the value for wx_student.gpa_img
     *
     * @mbggenerated Tue Feb 25 17:50:21 CST 2014
     */
    public void setGpaImg(byte[] gpaImg) {
        this.gpaImg = gpaImg;
    }

	public String getIdCardNum() {
		return idCardNum;
	}

	public void setIdCardNum(String idCardNum) {
		this.idCardNum = idCardNum;
	}
    
}