package ustc.yzwx.presentation.student.form;

public class Subscribe {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_subscribe.wx_code
     *
     * @mbggenerated Fri Mar 14 10:28:41 CST 2014
     */
    private String wxCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_subscribe.wx_code
     *
     * @return the value of wx_subscribe.wx_code
     *
     * @mbggenerated Fri Mar 14 10:28:41 CST 2014
     */
    public String getWxCode() {
        return wxCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_subscribe.wx_code
     *
     * @param wxCode the value for wx_subscribe.wx_code
     *
     * @mbggenerated Fri Mar 14 10:28:41 CST 2014
     */
    public void setWxCode(String wxCode) {
        this.wxCode = wxCode;
    }
}