package ustc.yzwx.presentation.activity.form;

import java.util.Date;
import java.util.List;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_activity.id
     *
     * @mbggenerated Wed Feb 19 09:53:20 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_activity.name
     *
     * @mbggenerated Wed Feb 19 09:53:20 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_activity.content
     *
     * @mbggenerated Wed Feb 19 09:53:20 CST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_activity.start_time
     *
     * @mbggenerated Wed Feb 19 09:53:20 CST 2014
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_activity.end_time
     *
     * @mbggenerated Wed Feb 19 09:53:20 CST 2014
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_activity.address
     *
     * @mbggenerated Wed Feb 19 09:53:20 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_activity.status
     *
     * @mbggenerated Wed Feb 19 09:53:20 CST 2014
     */
    private Short status;
    
    
    private String regionCode;
    
    /**
     * 该活动申请人数
     * 非数据库字段
     */
    private int applyCount;
    
    /**
     * 该活动签到人数
     * 非数据库字段
     */
    private int signCount;

    /**
     * 该活动下所有考生数
     */
    private int totalCount;
    
    /**
     * 活动代号
     */
    private String code;
    
    
    private Double lng;//经度
    private Double lat;//纬度
    
    private String type;//科学家报告会:report;夏令营：camp
    
    /** 院系 */
    private String majorCode;
  
    public String getMajorCode() {
		return majorCode;
	}

	public void setMajorCode(String majorCode) {
		this.majorCode = majorCode;
	}

	private List<ActivityBoardingInfo> boardingList;
    
    
    
    public List<ActivityBoardingInfo> getBoardingList() {
		return boardingList;
	}

	public void setBoardingList(List<ActivityBoardingInfo> boardingList) {
		this.boardingList = boardingList;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Double getLng() {
		return lng;
	}

	public void setLng(Double lng) {
		this.lng = lng;
	}

	public Double getLat() {
		return lat;
	}

	public void setLat(Double lat) {
		this.lat = lat;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

	public String getRegionCode() {
		return regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public int getApplyCount() {
		return applyCount;
	}

	public void setApplyCount(int applyCount) {
		this.applyCount = applyCount;
	}

	public int getSignCount() {
		return signCount;
	}

	public void setSignCount(int signCount) {
		this.signCount = signCount;
	}

	public int getTotalCount() {
		return totalCount;
	}

	public void setTotalCount(int totalCount) {
		this.totalCount = totalCount;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}
    
	
}