package com.zkhy.presentation.manager.form;

public class Manager {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_manager.manager_id
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	private Integer managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_manager.password
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_manager.roleStr
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	private String rolestr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_manager.manager_grade
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	private String managerGrade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_manager.manager_class
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	private String managerClass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_manager.userName
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_manager.status
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_manager.manager_id
	 * @return  the value of t_manager.manager_id
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public Integer getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_manager.manager_id
	 * @param managerId  the value for t_manager.manager_id
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public void setManagerId(Integer managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_manager.password
	 * @return  the value of t_manager.password
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_manager.password
	 * @param password  the value for t_manager.password
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_manager.roleStr
	 * @return  the value of t_manager.roleStr
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public String getRolestr() {
		return rolestr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_manager.roleStr
	 * @param rolestr  the value for t_manager.roleStr
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public void setRolestr(String rolestr) {
		this.rolestr = rolestr == null ? null : rolestr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_manager.manager_grade
	 * @return  the value of t_manager.manager_grade
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public String getManagerGrade() {
		return managerGrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_manager.manager_grade
	 * @param managerGrade  the value for t_manager.manager_grade
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public void setManagerGrade(String managerGrade) {
		this.managerGrade = managerGrade == null ? null : managerGrade.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_manager.manager_class
	 * @return  the value of t_manager.manager_class
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public String getManagerClass() {
		return managerClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_manager.manager_class
	 * @param managerClass  the value for t_manager.manager_class
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public void setManagerClass(String managerClass) {
		this.managerClass = managerClass == null ? null : managerClass.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_manager.userName
	 * @return  the value of t_manager.userName
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_manager.userName
	 * @param username  the value for t_manager.userName
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_manager.status
	 * @return  the value of t_manager.status
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_manager.status
	 * @param status  the value for t_manager.status
	 * @mbggenerated  Fri Apr 25 14:16:20 CST 2014
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}
}