package ustc.yzwx.presentation.student.form;

public class Major {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_major.id
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_major.code
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_major.parent_code
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_major.name
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_major.type
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    private Short type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_major.id
     *
     * @return the value of wx_major.id
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_major.id
     *
     * @param id the value for wx_major.id
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_major.code
     *
     * @return the value of wx_major.code
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_major.code
     *
     * @param code the value for wx_major.code
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_major.parent_code
     *
     * @return the value of wx_major.parent_code
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_major.parent_code
     *
     * @param parentCode the value for wx_major.parent_code
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_major.name
     *
     * @return the value of wx_major.name
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_major.name
     *
     * @param name the value for wx_major.name
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_major.type
     *
     * @return the value of wx_major.type
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_major.type
     *
     * @param type the value for wx_major.type
     *
     * @mbggenerated Wed Feb 19 15:45:12 CST 2014
     */
    public void setType(Short type) {
        this.type = type;
    }
}