package ustc.yzwx.presentation.student.form;

public class StudentMajor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student_major.id
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student_major.student_id
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_student_major.major_code
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    private String majorCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student_major.id
     *
     * @return the value of wx_student_major.id
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student_major.id
     *
     * @param id the value for wx_student_major.id
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student_major.student_id
     *
     * @return the value of wx_student_major.student_id
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student_major.student_id
     *
     * @param studentId the value for wx_student_major.student_id
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_student_major.major_code
     *
     * @return the value of wx_student_major.major_code
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    public String getMajorCode() {
        return majorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_student_major.major_code
     *
     * @param majorCode the value for wx_student_major.major_code
     *
     * @mbggenerated Fri Mar 28 09:44:58 CST 2014
     */
    public void setMajorCode(String majorCode) {
        this.majorCode = majorCode == null ? null : majorCode.trim();
    }
}