CREATE TABLE M_USER (
	USER_ID CHAR(5) PRIMARY KEY,
	PASSWORD CHAR(128) NOT NULL,
	USER_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE M_INTRODUCTION (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(20) NOT NULL,
	DETAIL VARCHAR(500) NOT NULL
);

CREATE TABLE T_TIMELINE (
	DATE_ID INT PRIMARY KEY AUTO_INCREMENT,
	DATE_START DATE NOT NULL,
	DATE_END DATE
);

CREATE TABLE T_TIMELINE_DETAIL (
	ACTIVITY_ID INT PRIMARY KEY AUTO_INCREMENT,
	DATE_ID INT,
	ACTIVITY_START TIME NOT NULL,
	ACTIVITY_END TIME,
	ACTIVITY_CONTENT VARCHAR(50) NOT NULL
);