package ustc.yzwx.integration.student.dao;

import java.util.List;

import ustc.yzwx.common.integration.dao.annotation.DaoMaster;
import ustc.yzwx.presentation.student.form.School;

@DaoMaster
public interface SchoolDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_school
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_school
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_school
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    int insertSelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_school
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    School selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_school
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    int updateByPrimaryKeySelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_school
     *
     * @mbggenerated Tue Feb 25 11:41:32 CST 2014
     */
    int updateByPrimaryKey(School record);
    
    /**
     * 查询全部学校
     * @return
     */
    List<School> selectAll();
}